language: cpp

dist: trusty
sudo: required

git:
  depth: 10

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/prepare.sh & ./util/osx/prepare.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/prepare.sh & sudo ./util/ubuntu/prepare.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/build.sh & ./util/osx/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/build.sh & ./util/ubuntu/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "O/E7evsNZtq3V1HNk2u+RwoEAKk7ukSFMEyhHxQbzoRZ3skrvYrIBtQMw1N/qqPKftUgtLlo214HmAnh8DzeqTDHx3M5NlXnBmDjm/d14lLX1Vemd3pKJIFY47Ml2HKieWh9oCksDrpxnY9Zkm1GMqZN8EaOUnvgkVUiORDqCD4D0i4inwdflVicBdFlrGK81Cu552InY7fFg2Ss2/8mpuKWCb1NIE/CReJjWXQogvHRP3nGB+mrlmHyognjHpavmcalnCLiiX7cEqOcR0Hdw7EGLN9alHONGlxES9qEV5Ydk0+T8Ccvp1MgWa406+oDQ949U+X8Vc4ZCyK9GLZ98/QVElJf7rH9YTt4Kso3Y0752v2a3Un+O+wlA9cEDbpwj5OpeEUKXBgy9tDYiLc8n1nL0xdFHsEJS1qTQcD3ZLlNnye+yYftCYRLKV5SPNqwUPYgE/YYpU5fZeuzDfiXc3H/fhmjV1CpVOdc9CVWgRLxtdmWfQi1VvPbTCThWnfQ6bfbfRaVkxihiRsWGhRe0yHVqOUzzkGkd4lhYa1zsn5RpF6yEfxQvnE/yAI2wvo3JaYIoVqTAkV1Tl9dZdfsmEh+MFgB1LZmEGWqaB0wY7vBY9SeDF3eqgAaIS5Hj1ArzFHVSa6rK/Klv89d3P+HvIq7FmQYRUM3YyIesubdVZY="
    file_glob: true
    file: "QtcGtest-*.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: change
